language: php

php:
  - 7.4

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - Build/Scripts/runTests.sh -s composerInstall -p $TRAVIS_PHP_VERSION

script:
  - >
    echo;
    echo "Running PHP codesniffer";
    .Build/bin/phpcs -n --standard=PSR2 --extensions=php --ignore=*./Tests/*,*./.Build/* .;

  - >
    echo "Running composer validate";
    Build/Scripts/runTests.sh -s composerValidate -p $TRAVIS_PHP_VERSION;

  - >
    echo "Running unit tests";
    Build/Scripts/runTests.sh -s unit -p $TRAVIS_PHP_VERSION;

  - >
    echo "Running php lint";
    Build/Scripts/runTests.sh -s lint -p $TRAVIS_PHP_VERSION;

  - >
    echo "Running functional tests";
    Build/Scripts/runTests.sh -s functional -p $TRAVIS_PHP_VERSION;
